#!/bin/bash

# Exit on command errors and treat unset variables as an error
#set -eu

#TRAP_ON () {    # Activate signal capture
#        trap EXIT_PROPERLY ERR  # Capturing ex it signals on error
#}

# Active trap pour arrêter le script si une erreur est détectée.
#TRAP_ON

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers

final_path=$(ynh_app_setting_get $app final_path)
path=$(ynh_app_setting_get $app path)
sitename=$(ynh_app_setting_get $app sitename)
domain=$(ynh_app_setting_get $app domain)
is_public=$(ynh_app_setting_get $app is_public)
finalnginxconf=$(ynh_app_setting_get $app finalnginxconf)
finalphpconf=$(ynh_app_setting_get $app finalphpconf)
db_create=$(ynh_app_setting_get $app db_create)


# Backup sources & data
# Note: the last argument is where to save this path, see the restore script.
ynh_backup "$final_path" "sources"

# Copy NGINX configuration
ynh_backup "$finalnginxconf" "nginx.conf"

### PHP (remove if not used) ###
# If a dedicated php-fpm process is used:
# # Copy PHP-FPM pool configuration
ynh_backup "$finalphpconf" "php-fpm.conf"

# Backup data base
if [ "$db_create" = "Yes" ];
then
	db_name=$(ynh_app_setting_get $app db_name)
	db_pwd=$(ynh_app_setting_get $app db_pwd)
	# Dump the database
	mysqldump -u "$db_name" -p"$db_pwd" --no-create-db "$db_name" > ./dump.sql
else
	echo "No database to backup"
fi
