#!/bin/bash
set -eu

# Charge les fonctions génériques habituellement utilisées dans le script
source .functions

# Active trap pour arrêter le script si une erreur est détectée.
#TRAP_ON

# Source app helpers
source /usr/share/yunohost/helpers

# Retrieve arguments
app=$YNH_APP_INSTANCE_NAME
domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
is_public=$YNH_APP_ARG_IS_PUBLIC

# We check variables are not empty
CHECK_VAR "$app" "app name not set"

# Check the path value and correct it (adds / at begining and removes it at the end)
CHECK_PATH
# Check domain and path availibility
CHECK_DOMAINPATH
# Check destination folder is not used already
CHECK_FINALPATH

# Definition of sitename for further use
if [ $path = "/" ]
then
	sitename="root"
else
	sitename=$(echo $path | cut -d '/' -f 2)
	# Removal of trailing /
	# path can be null but not really an issue for the remaining commands
	path=${path%/}
fi

final_path=/var/www/webapp\_multi/$domain/$sitename

# Save app settings
ynh_app_setting_set "$app" domain "$domain"
ynh_app_setting_set "$app" is_public "$is_public"
ynh_app_setting_set "$app" sitename "$sitename"
ynh_app_setting_set "$app" final_path "$final_path"


# Creation of folder
#sudo rm -rf $final_path
sudo mkdir -p $final_path

# Base site
sed -i "s@DOMAINTOCHANGE@$domain@g" ../sources/index.html
sed -i "s@SITETOCHANGE@$sitename@g" ../sources/index.html
sudo cp ../sources/* $final_path/

# Set permissions
sudo chmod 775 /var/www/webapp\_multi
sudo chmod 775 /var/www/webapp\_multi/$domain
sudo chmod 775 -R $final_path
sudo chown www-data:www-data /var/www/webapp\_multi
sudo chown www-data:www-data /var/www/webapp\_multi/$domain
sudo chown -hR www-data:www-data $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sed -i "s@NAMETOCHANGE@$domain\_$sitename@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$sitename.conf

sed -i "s@NAMETOCHANGE@$domain\_$sitename@g" ../conf/php-fpm.conf
sed -i "s@FOLDERTOCHANGE@webapp\_multi/$domain/$sitename@g" ../conf/php-fpm.conf
finalphpconf=/etc/php5/fpm/pool.d/$domain\_$sitename.conf
sudo cp ../conf/php-fpm.conf $finalphpconf
sudo chown root: $finalphpconf
sudo chmod 644 $finalphpconf

# Make app public if necessary
is_public=$(ynh_app_setting_get nom_app is_public)
if [ "$is_public" = "Yes" ];
then
	ynh_app_setting_set $app skipped_uris "/"
fi

# Reload Nginx and regenerate SSOwat conf
sudo service php5-fpm reload
sudo service nginx reload
sudo yunohost app ssowatconf
