#!/bin/bash

app=webapp_multi

user=$(sudo yunohost app setting $app user)
path=$(sudo yunohost app setting $app path)
domain=$(sudo yunohost app setting $app domain)
final_path=$(sudo yunohost app setting $app final_path)

sitename=$(echo $path | cut -d '/' -f 2)

# Suppression du dossier de la webapp
sudo rm -rf $final_path

# Suppression de la config nginx de la webapp
sudo rm -f /etc/nginx/conf.d/$domain.d/$sitename.conf

# Vérifie si le dossier parent est vide. Ce qui signifie que toutes les webapp ont été désinstallées. Ainsi que le client ftp net2ftp.
#if test -z "$(ls $parent_dir | head -n1)"
#then
#    sudo rmdir $parent_dir
#fi

sudo service nginx reload
sudo yunohost app ssowatconf
