#!/bin/bash

#app=webapp_multi_inst
app=$YNH_APP_INSTANCE_NAME

#user=$(sudo yunohost app setting $app user)
path=$(sudo yunohost app setting $app path)
sitename=$(sudo yunohost app setting $app sitename)
domain=$(sudo yunohost app setting $app domain)
final_path=$(sudo yunohost app setting $app final_path)


# Suppression du dossier de la webapp
sudo rm -rf $final_path

# Suppression de la config nginx de la webapp
sudo rm -f /etc/nginx/conf.d/$domain.d/$sitename.conf
sudo rm -f /etc/php5/fpm/pool.d/$domain\_$sitename.conf

# We check if folders are empty and if yes we delete them
#
#if test -z "$(ls /var/www/webapp_multi/$domain | head -n1)"
#then
#	sudo rmdir /var/www/webapp_multi/$domain
#fi
sudo rmdir --ignore-fail-on-non-empty /var/www/webapp_multi/$domain

#if test -z "$(ls /var/www/webapp_multi/ | head -n1)"
#then
#	sudo rmdir /var/www/webapp_multi
#fi
sudo rmdir --ignore-fail-on-non-empty /var/www/webapp_multi


sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app ssowatconf
