#!/bin/bash

# Note: each files and directories you've saved using the ynh_backup helper
# will be located in the current directory, regarding the last argument.

# Exit on command errors and treat unset variables as an error
#set -eu

#TRAP_ON () {    # Activate signal capture
#        trap EXIT_PROPERLY ERR  # Capturing ex it signals on error
#}

# Active trap pour arrêter le script si une erreur est détectée.
#TRAP_ON

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve old app settings
final_path=$(ynh_app_setting_get $app final_path)
path=$(ynh_app_setting_get $app path)
sitename=$(ynh_app_setting_get $app sitename)
domain=$(ynh_app_setting_get $app domain)
is_public=$(ynh_app_setting_get $app is_public)
finalnginxconf=$(ynh_app_setting_get $app finalnginxconf)
finalphpconf=$(ynh_app_setting_get $app finalphpconf)
db_create=$(ynh_app_setting_get $app db_create)

# Restore sources & data
sudo mkdir -p $final_path
sudo cp -a ./sources/* $final_path/

# Restore permissions to app files
# you may need to make some file and/or directory writeable by www-data (nginx user)
sudo chown -R www-data:www-data $final_path

# Restore NGINX configuration
sudo cp -a ./nginx.conf $finalnginxconf

### PHP (remove if not used) ###
# If a dedicated php-fpm process is used:
# # Copy PHP-FPM pool configuration and reload the service
sudo cp -a ./php-fpm.conf $finalphpconf
### PHP end ###

# Restore db if required
if [ "$db_create" = "Yes" ];
then
	# Create and restore the database
	db_name=$(ynh_app_setting_get $app db_name)
	db_pwd=$(ynh_app_setting_get $app db_pwd)
	ynh_mysql_create_db "$db_name" "$db_name" "$db_pwd"
	ynh_mysql_connect_as "$db_name" "$db_pwd" "$db_name" < ./dump.sql
else
	echo "No need to backup database";
fi

# Make app public if necessary
is_public=$(ynh_app_setting_get $app is_public)
if [ "$is_public" = "Yes" ];
then
        ynh_app_setting_set $app skipped_uris "/"
else
        ynh_app_setting_set $app protected_uris "/"
fi


# Restart webserver
sudo service nginx reload
sudo service php5-fpm reload
sudo yunohost app ssowatconf

