#!/bin/bash

# Retrieve arguments
app=webapp_multi_inst

domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
sitename=$(sudo yunohost app setting $app sitename)
#user=$(sudo yunohost app setting $app user)
is_public=$(sudo yunohost app setting $app is_public)
final_path=$(sudo yunohost app setting $app final_path)


#netftp_path=/ftp_webapp_$user

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$name.conf

# Make app public if necessary
sudo yunohost app setting $app is_public -v "$is_public"
if [ "$is_public" = "Yes" ];
then
    sudo yunohost app setting $app skipped_uris -v "/"
else
    sudo yunohost app setting $app protected_uris -v "/"
fi

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf
